name: Publish Documentation
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Generate HTML docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate

          python -m pip install .[dev]
          sudo apt update
          sudo apt install -y latexmk texlive-fonts-recommended texlive-latex-extra texlive-pictures

      - name: Generate docs
        shell: bash
        run: |
          source venv/bin/activate
          make docs
          
          # set vars for output dirs
          DOCS_OUT="docs/build"
          DOCS_HTML="$DOCS_OUT/dirhtml"
          
          # create empty dir in HTML docs site
          mkdir -p "$DOCS_HTML/files/"
          # move other formats into the HTML docs
          mv \
            "$DOCS_OUT"/pdf/*.pdf \
            "$DOCS_OUT"/epub/*.epub \
            "$DOCS_HTML"/files/
          # pack everything up for further distribution
          tar \
            --dereference --hard-dereference \
            --directory "$DOCS_HTML" \
            -czvf "$RUNNER_TEMP/docs.tgz" \
            .
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/docs.tgz
          retention-days: 1
          if-no-files-found: error

  deploy-gh-pages:
    name: Publish docs to GH-Pages

    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # only publish new docs on tag pushes
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
